/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain */
        get: operations["explain_api_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Weather */
        get: operations["current_weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Advice */
        get: operations["advice_api_advice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare-mandis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Mandis */
        get: operations["compare_mandis_api_compare_mandis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offer-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer Check */
        post: operations["offer_check_api_offer_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/margin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Margin */
        get: operations["margin_api_margin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crop-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crop Plan */
        get: operations["crop_plan_api_crop_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/farmers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_farmers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/farmers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_farmers_me_get"];
        /** Update Me */
        put: operations["update_me_api_farmers_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify */
        get: operations["verify_webhooks_whatsapp_get"];
        put?: never;
        /** Receive */
        post: operations["receive_webhooks_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdviceResponse */
        AdviceResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Quantity Maund */
            quantity_maund: number;
            /**
             * Signal
             * @enum {string}
             */
            signal: "SELL" | "WAIT";
            /** Signal Ur */
            signal_ur: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            /**
             * Trend
             * @enum {string}
             */
            trend: "UP" | "DOWN" | "STABLE";
            /** Current Price */
            current_price: number;
            /** Predicted Price */
            predicted_price: number;
            range: components["schemas"]["PriceRange"];
            /** Gross Gain */
            gross_gain: number;
            /** Interest Cost */
            interest_cost: number;
            /** Rupee Impact */
            rupee_impact: number;
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Is Stale */
            is_stale: boolean;
            /** Price Unchanged Since */
            price_unchanged_since: string | null;
            /** Model */
            model: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Crop */
            crop?: ("wheat" | "cotton" | "irri" | "super_basmati") | null;
            /** Mandi */
            mandi?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Quantity Maund */
            quantity_maund?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Used Fallback */
            used_fallback: boolean;
            /** Fallback Reason */
            fallback_reason: ("need_crop_and_mandi" | "no_data" | "service_not_ready" | "rate_limited" | "llm_unavailable" | "unverified_numbers" | "wrong_script") | null;
            /** Crop */
            crop: ("wheat" | "cotton" | "irri" | "super_basmati") | null;
            /** Mandi */
            mandi: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * From Mandi
             * @enum {string}
             */
            from_mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Quantity Maund */
            quantity_maund: number;
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
            /** Transport Is Estimate */
            transport_is_estimate: boolean;
        };
        /** CompareRow */
        CompareRow: {
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Has Data */
            has_data: boolean;
            /** Price */
            price?: number | null;
            /** Transport Cost */
            transport_cost?: number | null;
            /** Net Price */
            net_price?: number | null;
            /** Gain Vs Preferred */
            gain_vs_preferred?: number | null;
            /** Prices As Of */
            prices_as_of?: string | null;
            /** Is Stale */
            is_stale?: boolean | null;
        };
        /** CropInfo */
        CropInfo: {
            /** Id */
            id: string;
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
            /**
             * Season
             * @enum {string}
             */
            season: "RABI" | "KHARIF";
            /** Sowing Months */
            sowing_months: [
                number,
                number
            ];
            /** Harvest Months */
            harvest_months: [
                number,
                number
            ];
        };
        /** CropPlanItem */
        CropPlanItem: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /** Rank */
            rank: number;
            /** Latest Price */
            latest_price: number;
            /**
             * Latest Price Date
             * Format: date
             */
            latest_price_date: string;
            /** Harvest Price Estimate */
            harvest_price_estimate: number;
            /** Harvest Price Low */
            harvest_price_low: number;
            /** Harvest Price High */
            harvest_price_high: number;
            /** Months Ahead */
            months_ahead: number;
            /** Yield Maund Per Acre */
            yield_maund_per_acre: number;
            /** Cost Per Acre */
            cost_per_acre: number;
            /** Profit Per Acre */
            profit_per_acre: number;
            /** Expected Profit */
            expected_profit: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "LOW" | "MEDIUM" | "HIGH";
            /** Spread Pct */
            spread_pct: number | null;
            /** N Years */
            n_years: number;
            /** Sowing Months */
            sowing_months: [
                number,
                number
            ];
            /** Harvest Months */
            harvest_months: [
                number,
                number
            ];
            /** Best Sell Month */
            best_sell_month: number | null;
            /** Best Sell Gain Pct */
            best_sell_gain_pct: number | null;
            /** Is Stale */
            is_stale: boolean;
        };
        /** CropPlanResponse */
        CropPlanResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Land Area Acres */
            land_area_acres: number;
            /** Items */
            items: components["schemas"]["CropPlanItem"][];
            /** Not Available */
            not_available: ("wheat" | "cotton" | "irri" | "super_basmati")[];
            /** Is Estimate */
            is_estimate: boolean;
        };
        /** DataSourceInfo */
        DataSourceInfo: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Covers */
            covers: string;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /**
             * Source
             * @enum {string}
             */
            source: "shap" | "facts";
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
        };
        /** Farmer */
        Farmer: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Language
             * @enum {string}
             */
            language: "ur" | "en";
            /**
             * District
             * @enum {string}
             */
            district: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Land Area Acres */
            land_area_acres: number | null;
            /** Arhti Commission Pct */
            arhti_commission_pct: number | null;
            /** Alerts Enabled */
            alerts_enabled: boolean;
            /** Crops */
            crops: components["schemas"]["FarmerCropIn"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FarmerCropIn */
        FarmerCropIn: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Preferred Mandi
             * @enum {string}
             */
            preferred_mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Harvest Quantity Maund */
            harvest_quantity_maund: number;
        };
        /** FarmerIn */
        FarmerIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Language
             * @default ur
             * @enum {string}
             */
            language: "ur" | "en";
            /**
             * District
             * @enum {string}
             */
            district: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Land Area Acres */
            land_area_acres?: number | null;
            /** Arhti Commission Pct */
            arhti_commission_pct?: number | null;
            /**
             * Alerts Enabled
             * @default true
             */
            alerts_enabled: boolean;
            /** Crops */
            crops?: components["schemas"]["FarmerCropIn"][];
        };
        /** FarmerUpdate */
        FarmerUpdate: {
            /** Name */
            name?: string | null;
            /** Language */
            language?: ("ur" | "en") | null;
            /** District */
            district?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Land Area Acres */
            land_area_acres?: number | null;
            /** Arhti Commission Pct */
            arhti_commission_pct?: number | null;
            /** Alerts Enabled */
            alerts_enabled?: boolean | null;
            /** Crops */
            crops?: components["schemas"]["FarmerCropIn"][] | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Current Price */
            current_price: number;
            /** Predicted Price */
            predicted_price: number;
            range: components["schemas"]["PriceRange"];
            /** Horizon Weeks */
            horizon_weeks: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "UP" | "DOWN" | "STABLE";
            /**
             * Volatility
             * @enum {string}
             */
            volatility: "STABLE" | "MODERATE" | "VOLATILE";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            /** Model */
            model: string;
            /** Is Stale */
            is_stale: boolean;
            /** Price Unchanged Since */
            price_unchanged_since: string | null;
            /** History */
            history: components["schemas"]["PricePoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Weekly */
            weekly: components["schemas"]["PricePoint"][];
            /** Seasonal */
            seasonal: components["schemas"]["SeasonalPoint"][];
            /** Sowing Months */
            sowing_months: [
                number,
                number
            ];
            /** Harvest Months */
            harvest_months: [
                number,
                number
            ];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Phone */
            phone: string;
        };
        /** MarginResponse */
        MarginResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Price */
            price: number;
            /** Production Cost */
            production_cost: number;
            /** Cost Confidence */
            cost_confidence: string;
            /** Arhti Pct */
            arhti_pct: number;
            /** Arhti Amount */
            arhti_amount: number;
            /** Profit */
            profit: number;
            /** Support Price */
            support_price: number | null;
            /** Support Status */
            support_status: string | null;
            /** Support Crop Year */
            support_crop_year: string | null;
        };
        /** Meta */
        Meta: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Price Type
             * @constant
             */
            price_type: "wholesale";
            /** Crops */
            crops: components["schemas"]["CropInfo"][];
            /** Mandis */
            mandis: components["schemas"]["NamedItem"][];
            /** Series */
            series: components["schemas"]["SeriesInfo"][];
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Horizon Weeks */
            horizon_weeks: number;
            /** Wait Threshold Pct */
            wait_threshold_pct: number;
            /** Interest Pct Per Month */
            interest_pct_per_month: number;
            /** Sources */
            sources: components["schemas"]["DataSourceInfo"][];
        };
        /** NamedItem */
        NamedItem: {
            /** Id */
            id: string;
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
        };
        /** OfferCheckRequest */
        OfferCheckRequest: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Offer Price */
            offer_price: number;
            /**
             * Quantity Maund
             * @default 100
             */
            quantity_maund: number;
        };
        /** OfferCheckResponse */
        OfferCheckResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Offer Price */
            offer_price: number;
            /** Fair Low */
            fair_low: number;
            /** Fair High */
            fair_high: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "below" | "fair" | "above";
            /** Difference Per Maund */
            difference_per_maund: number;
            /** Difference Total */
            difference_total: number;
            /** Window Days */
            window_days: number;
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
        };
        /** PriceRange */
        PriceRange: {
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /** Reason */
        Reason: {
            /** Text Ur */
            text_ur: string;
            /** Text En */
            text_en: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "UP" | "DOWN" | "";
        };
        /** SeasonalPoint */
        SeasonalPoint: {
            /** Month */
            month: number;
            /** Index Median */
            index_median: number | null;
            /** Index Min */
            index_min: number | null;
            /** Index Max */
            index_max: number | null;
            /** N Years */
            n_years: number;
        };
        /** SeriesInfo */
        SeriesInfo: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Latest Price */
            latest_price: number;
            /** Is Stale */
            is_stale: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
            farmer: components["schemas"]["Farmer"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherNow */
        WeatherNow: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Tmax C */
            tmax_c: number | null;
            /** Tmin C */
            tmin_c: number | null;
            /** Precip Mm Wk */
            precip_mm_wk: number | null;
            /** Rh Pct */
            rh_pct: number | null;
            /** Precip Mm 4W */
            precip_mm_4w: number | null;
            /** Hot Days Wk */
            hot_days_wk: number | null;
            /** Cached */
            cached: boolean;
            /** Source */
            source: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Attribution */
            attribution: string;
        };
        /** WeatherResponse */
        WeatherResponse: {
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            weather: components["schemas"]["WeatherNow"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    forecast_api_forecast_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_api_explain_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_weather_api_weather_get: {
        parameters: {
            query: {
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advice_api_advice_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Maund. Default: profile, else 100. */
                quantity_maund?: number | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_mandis_api_compare_mandis_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Maund. Default: profile, else 100. */
                quantity_maund?: number | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_check_api_offer_check_post: {
        parameters: {
            query?: {
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    margin_api_margin_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                price: number;
                arhti_pct?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crop_plan_api_crop_plan_get: {
        parameters: {
            query?: {
                mandi?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
                land_area_acres?: number | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_farmers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_farmers_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farmer"];
                };
            };
        };
    };
    update_me_api_farmers_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farmer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_webhooks_whatsapp_get: {
        parameters: {
            query?: {
                "hub.mode"?: string;
                "hub.verify_token"?: string;
                "hub.challenge"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_webhooks_whatsapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
