/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advice */
        post: operations["advice_api_advice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay */
        get: operations["replay_api_replay__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest */
        get: operations["backtest_api_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify */
        get: operations["verify_webhooks_whatsapp_get"];
        put?: never;
        /** Receive */
        post: operations["receive_webhooks_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdviceRequest */
        AdviceRequest: {
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
            /** Quantity Maund */
            quantity_maund: number;
            /**
             * Storage
             * @enum {string}
             */
            storage: "none" | "home" | "cold_store" | "warehouse";
            /** Storage Cost Per Maund Week */
            storage_cost_per_maund_week?: number | null;
            /** Spoilage Pct Week */
            spoilage_pct_week?: number | null;
            /** Finance Cost Pct Month */
            finance_cost_pct_month?: number | null;
            /** As Of */
            as_of?: string | null;
            /**
             * Lang
             * @default ur
             * @enum {string}
             */
            lang: "ur" | "en";
        };
        /** AdviceResponse */
        AdviceResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "sell_now" | "sell_elsewhere" | "store" | "split";
            /** Verdict Text */
            verdict_text: string;
            /** Rupee Difference */
            rupee_difference: number;
            /** Best Week */
            best_week: number;
            /** Reasons */
            reasons: string[];
            /** Risk Line */
            risk_line: string;
            alternative_mandi: components["schemas"]["AlternativeMandi"] | null;
            /** Alerts */
            alerts: components["schemas"]["EventRef"][];
            /** Alarm Tier */
            alarm_tier: ("normal" | "stress" | "alert" | "crisis") | null;
            /** Assumptions */
            assumptions: components["schemas"]["AssumptionUsed"][];
        };
        /** Alarm */
        Alarm: {
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Indicator */
            indicator: number;
            /**
             * Tier
             * @enum {string}
             */
            tier: "normal" | "stress" | "alert" | "crisis";
            /** Flags */
            flags: ("below_3yr_harvest_avg" | "yoy_drop_over_50pct")[];
        };
        /** AlertsResponse */
        AlertsResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Crop */
            crop: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Alarms */
            alarms: components["schemas"]["Alarm"][];
            /** Events */
            events: components["schemas"]["Event"][];
        };
        /** AlternativeMandi */
        AlternativeMandi: {
            /** Mandi */
            mandi: string;
            /** Net Price */
            net_price: number;
        };
        /** AssumptionUsed */
        AssumptionUsed: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /**
             * Source
             * @enum {string}
             */
            source: "farmer" | "default";
        };
        /** AssumptionValue */
        AssumptionValue: {
            /** Value */
            value: number;
            /** Source */
            source: string;
        };
        /** Assumptions */
        Assumptions: {
            finance_cost_pct_month: components["schemas"]["AssumptionValue"];
            /** Storage Defaults */
            storage_defaults: components["schemas"]["StorageDefault"][];
            /** Transport */
            transport: components["schemas"]["TransportCost"][];
        };
        /** BacktestArtifact */
        BacktestArtifact: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Horizon Weeks */
            horizon_weeks: number;
            /** Cutoffs */
            cutoffs: string[];
            /** Metrics */
            metrics: components["schemas"]["MetricRow"][];
            rupee_backtest: components["schemas"]["RupeeBacktest"] | null;
            /** Limitations */
            limitations: string[];
        };
        /** BandPoint */
        BandPoint: {
            /** Weeks Ahead */
            weeks_ahead: number;
            /** Q10 */
            q10: number;
            /** Q50 */
            q50: number;
            /** Q90 */
            q90: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Crop Option */
            crop_option?: ("Wheat" | "Cotton" | "IRRI" | "SuperBasmati") | null;
            /** Mandi */
            mandi?: ("BahawalPur" | "Vehari" | "RahimYarKhan") | null;
            /** Quantity Maund */
            quantity_maund?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Used Fallback */
            used_fallback: boolean;
            /** Fallback Reason */
            fallback_reason: ("need_crop_and_mandi" | "no_data" | "service_not_ready" | "rate_limited" | "llm_unavailable" | "unverified_numbers" | "wrong_script") | null;
            /** Crop Option */
            crop_option: string | null;
            /** Mandi */
            mandi: string | null;
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
        };
        /** DateRange */
        DateRange: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** Event */
        Event: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Active Until
             * Format: date
             */
            active_until: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "border_closure" | "export_ban" | "import_permission" | "procurement_policy" | "flood" | "drought" | "bumper_crop" | "transport_disruption" | "other";
            /** Crops */
            crops: string[];
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "unclear";
            /** Region */
            region: string;
            /** Headline */
            headline: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Is Synthetic */
            is_synthetic: boolean;
        };
        /** EventRef */
        EventRef: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "border_closure" | "export_ban" | "import_permission" | "procurement_policy" | "flood" | "drought" | "bumper_crop" | "transport_disruption" | "other";
            /** Headline */
            headline: string;
            /** Source Url */
            source_url: string | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Price Now */
            price_now: number;
            /** History */
            history: components["schemas"]["PricePoint"][];
            /** Forecast */
            forecast: components["schemas"]["BandPoint"][];
            /** Naive */
            naive: components["schemas"]["NaivePoint"][];
            /** Model */
            model: string;
            /** Mase Vs Naive */
            mase_vs_naive: number | null;
            /**
             * Price Type
             * @enum {string}
             */
            price_type: "wholesale" | "retail";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Meta */
        Meta: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /**
             * Generated At
             * Format: date
             */
            generated_at: string;
            /** Crops */
            crops: components["schemas"]["NamedItem"][];
            /** Mandis */
            mandis: components["schemas"]["NamedItem"][];
            /** Series */
            series: components["schemas"]["SeriesKey"][];
            /** Replay Cases */
            replay_cases: components["schemas"]["ReplayCaseRef"][];
            date_range: components["schemas"]["DateRange"];
            /**
             * Latest As Of
             * Format: date
             */
            latest_as_of: string;
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Price Type
             * @enum {string}
             */
            price_type: "wholesale" | "retail";
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            assumptions: components["schemas"]["Assumptions"];
        };
        /** MetricRow */
        MetricRow: {
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
            /** Model */
            model: string;
            /** Mase */
            mase: number | null;
            /** Quantile Loss */
            quantile_loss: number | null;
            /** Coverage 80 */
            coverage_80: number | null;
            /** N Forecasts */
            n_forecasts: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Role
             * @enum {string}
             */
            role: "primary" | "challenger" | "baseline" | "placeholder";
        };
        /** NaivePoint */
        NaivePoint: {
            /** Weeks Ahead */
            weeks_ahead: number;
            /** Price */
            price: number;
        };
        /** NamedAssumption */
        NamedAssumption: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Source */
            source: string;
        };
        /** NamedItem */
        NamedItem: {
            /** Id */
            id: string;
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
        };
        /** ReplayCaseRef */
        ReplayCaseRef: {
            /** Case Id */
            case_id: string;
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
            /** Title Ur */
            title_ur: string;
            /** Title En */
            title_en: string;
        };
        /** ReplayResponse */
        ReplayResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Case Id */
            case_id: string;
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Steps */
            steps: components["schemas"]["ReplayStep"][];
        };
        /** ReplayStep */
        ReplayStep: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Price Now */
            price_now: number;
            /** Forecast Q10 */
            forecast_q10: number;
            /** Forecast Q50 */
            forecast_q50: number;
            /** Forecast Q90 */
            forecast_q90: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "sell_now" | "sell_elsewhere" | "store" | "split";
            /**
             * Alarm Tier
             * @enum {string}
             */
            alarm_tier: "normal" | "stress" | "alert" | "crisis";
            /** Events Active */
            events_active: components["schemas"]["EventRef"][];
            /** Actual Price 4W Later */
            actual_price_4w_later?: number | null;
        };
        /** RupeeBacktest */
        RupeeBacktest: {
            /** Quantity Maund */
            quantity_maund: number;
            /** N Cases */
            n_cases: number;
            /** Avg Gain Vs Harvest Pkr */
            avg_gain_vs_harvest_pkr: number;
            /** Share Better */
            share_better: number;
            /** Worst Case Pkr */
            worst_case_pkr: number;
            /** Hindsight Avg Gain Pkr */
            hindsight_avg_gain_pkr: number;
            /** Assumptions */
            assumptions: components["schemas"]["NamedAssumption"][];
        };
        /** SeriesKey */
        SeriesKey: {
            /** Crop */
            crop: string;
            /** Mandi */
            mandi: string;
        };
        /** StorageDefault */
        StorageDefault: {
            /** Crop */
            crop: string;
            /**
             * Storage
             * @enum {string}
             */
            storage: "home" | "cold_store" | "warehouse";
            /** Storage Cost Per Maund Week */
            storage_cost_per_maund_week: number;
            /** Spoilage Pct Week */
            spoilage_pct_week: number;
            /** Source */
            source: string;
        };
        /** TransportCost */
        TransportCost: {
            /** From Mandi */
            from_mandi: string;
            /** To Mandi */
            to_mandi: string;
            /** Cost Per Maund */
            cost_per_maund: number;
            /** Source */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    forecast_api_forecast_get: {
        parameters: {
            query: {
                crop: string;
                mandi: string;
                /** @description Latest data on or before this date. Omit for latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advice_api_advice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query: {
                crop: string;
                mandi?: string | null;
                /** @description Latest data on or before this date. Omit for latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_api_replay__case_id__get: {
        parameters: {
            query?: {
                lang?: "ur" | "en";
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestArtifact"];
                };
            };
        };
    };
    verify_webhooks_whatsapp_get: {
        parameters: {
            query?: {
                "hub.mode"?: string;
                "hub.verify_token"?: string;
                "hub.challenge"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_webhooks_whatsapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
