/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain */
        get: operations["explain_api_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Weather */
        get: operations["current_weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Advice */
        get: operations["advice_api_advice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare-mandis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Mandis */
        get: operations["compare_mandis_api_compare_mandis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offer-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer Check */
        post: operations["offer_check_api_offer_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/margin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Margin */
        get: operations["margin_api_margin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crop-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crop Plan */
        get: operations["crop_plan_api_crop_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wait-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wait Plan */
        get: operations["wait_plan_api_wait_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * News
         * @description Today's Pakistan farm news (not replayed with as_of: like weather, it is always today's). News never
         *     changes the advice; it can only add a warning or lower confidence (docs/PIVOT.md rule 8).
         */
        get: operations["news_api_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy */
        get: operations["policy_api_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loan-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Loan Plan
         * @description What the crop actually needs, the cheapest money first, and what over-borrowing costs. Placeholder numbers
         *     until D1/D2/B2 (docs/PIVOT.md 3.4): the shape and labelling are final.
         */
        get: operations["loan_plan_api_loan_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/farmers/me/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Loans */
        get: operations["my_loans_api_farmers_me_loans_get"];
        put?: never;
        /** Add My Loan */
        post: operations["add_my_loan_api_farmers_me_loans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/farmers/me/loans/{loan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete My Loan */
        delete: operations["delete_my_loan_api_farmers_me_loans__loan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Alerts
         * @description Runs one alert check now (the schedule runs it too when FS_ALERTS_EVERY_HOURS is set). For the team only:
         *     needs the X-Admin-Token header to equal FS_ADMIN_TOKEN. `dry_run` shows the messages without sending.
         */
        post: operations["run_alerts_api_alerts_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/farmers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_farmers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/farmers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_farmers_me_get"];
        /** Update Me */
        put: operations["update_me_api_farmers_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify */
        get: operations["verify_webhooks_whatsapp_get"];
        put?: never;
        /** Receive */
        post: operations["receive_webhooks_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/sms/textbee/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive */
        post: operations["receive_api_channels_sms_textbee_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/sms/simpapp/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive */
        post: operations["receive_api_channels_sms_simpapp_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdviceResponse */
        AdviceResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Quantity Maund */
            quantity_maund: number;
            /**
             * Signal
             * @enum {string}
             */
            signal: "SELL" | "WAIT";
            /** Signal Ur */
            signal_ur: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            /**
             * Trend
             * @enum {string}
             */
            trend: "UP" | "DOWN" | "STABLE";
            /** Current Price */
            current_price: number;
            /** Predicted Price */
            predicted_price: number;
            range: components["schemas"]["PriceRange"];
            /** Gross Gain */
            gross_gain: number;
            /** Interest Cost */
            interest_cost: number;
            /** Rupee Impact */
            rupee_impact: number;
            /** Arhti Pct */
            arhti_pct?: number | null;
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Is Stale */
            is_stale: boolean;
            /** Price Unchanged Since */
            price_unchanged_since: string | null;
            direction?: components["schemas"]["DirectionCall"] | null;
            /** Model */
            model: string;
        };
        /** AlertItem */
        AlertItem: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Kind
             * @enum {string}
             */
            kind: "SELL_SIGNAL" | "PRICE_SPIKE";
            /**
             * Signal
             * @enum {string}
             */
            signal: "SELL" | "WAIT";
            /** Current Price */
            current_price: number;
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Change 4W Pct */
            change_4w_pct?: number | null;
        };
        /** AlertResult */
        AlertResult: {
            /** Farmer Id */
            farmer_id: string;
            /** Items */
            items: components["schemas"]["AlertItem"][];
            /** Suppressed */
            suppressed: number;
            /** Skipped */
            skipped: ("weekly_limit" | "no_event") | null;
            /** Message */
            message?: string | null;
            /** Status */
            status?: ("SENT" | "FAILED") | null;
            /** Channel */
            channel?: ("whatsapp" | "sms") | null;
        };
        /** AlertRunResponse */
        AlertRunResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Dry Run */
            dry_run: boolean;
            /** Farmers Checked */
            farmers_checked: number;
            /** Sent */
            sent: number;
            /** Results */
            results: components["schemas"]["AlertResult"][];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Crop */
            crop?: ("wheat" | "cotton" | "irri" | "super_basmati") | null;
            /** Mandi */
            mandi?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Quantity Maund */
            quantity_maund?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Used Fallback */
            used_fallback: boolean;
            /** Fallback Reason */
            fallback_reason: ("need_crop_and_mandi" | "no_data" | "service_not_ready" | "rate_limited" | "llm_unavailable" | "unverified_numbers" | "wrong_script") | null;
            /** Crop */
            crop: ("wheat" | "cotton" | "irri" | "super_basmati") | null;
            /** Mandi */
            mandi: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * From Mandi
             * @enum {string}
             */
            from_mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Quantity Maund */
            quantity_maund: number;
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
            /** Transport Is Estimate */
            transport_is_estimate: boolean;
        };
        /** CompareRow */
        CompareRow: {
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Has Data */
            has_data: boolean;
            /** Price */
            price?: number | null;
            /** Transport Cost */
            transport_cost?: number | null;
            /** Net Price */
            net_price?: number | null;
            /** Gain Vs Preferred */
            gain_vs_preferred?: number | null;
            /** Prices As Of */
            prices_as_of?: string | null;
            /** Is Stale */
            is_stale?: boolean | null;
        };
        /** ContextNote */
        ContextNote: {
            /**
             * Id
             * @constant
             */
            id: "RICE_WATER_BAHAWALPUR";
            /** Source */
            source: string;
            /**
             * Source Date
             * Format: date
             */
            source_date: string;
            /** Url */
            url: string;
        };
        /** CropInfo */
        CropInfo: {
            /** Id */
            id: string;
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
            /**
             * Season
             * @enum {string}
             */
            season: "RABI" | "KHARIF";
            /** Sowing Months */
            sowing_months: [
                number,
                number
            ];
            /** Harvest Months */
            harvest_months: [
                number,
                number
            ];
        };
        /** CropPlanItem */
        CropPlanItem: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /** Rank */
            rank: number | null;
            /**
             * Season
             * @enum {string}
             */
            season: "RABI" | "KHARIF";
            /** Latest Price */
            latest_price: number;
            /**
             * Latest Price Date
             * Format: date
             */
            latest_price_date: string;
            /** Harvest Price Estimate */
            harvest_price_estimate: number;
            /** Harvest Price Low */
            harvest_price_low: number;
            /** Harvest Price High */
            harvest_price_high: number;
            /** Months Ahead */
            months_ahead: number;
            /** Yield Maund Per Acre */
            yield_maund_per_acre: number;
            /** Cost Per Acre */
            cost_per_acre: number;
            /** Profit Per Acre */
            profit_per_acre: number;
            /** Expected Profit */
            expected_profit: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "LOW" | "MEDIUM" | "HIGH";
            /** Spread Pct */
            spread_pct: number | null;
            /** N Years */
            n_years: number;
            /** Sowing Months */
            sowing_months: [
                number,
                number
            ];
            /** Harvest Months */
            harvest_months: [
                number,
                number
            ];
            /** Best Sell Month */
            best_sell_month: number | null;
            /** Best Sell Gain Pct */
            best_sell_gain_pct: number | null;
            /** Sell At Harvest */
            sell_at_harvest: boolean;
            /** Sell Window Months */
            sell_window_months: number[];
            /** Profit Per Acre Low */
            profit_per_acre_low: number;
            /** Profit Per Acre High */
            profit_per_acre_high: number;
            /** Is Stale */
            is_stale: boolean;
            /** Is Frozen */
            is_frozen: boolean;
            /** Evidence Issues */
            evidence_issues: ("STALE_PRICE" | "FROZEN_PRICE" | "FEW_YEARS")[];
            /** Notes */
            notes: components["schemas"]["ContextNote"][];
        };
        /** CropPlanResponse */
        CropPlanResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Land Area Acres */
            land_area_acres: number;
            /** Items */
            items: components["schemas"]["CropPlanItem"][];
            /** Seasons */
            seasons: components["schemas"]["CropPlanSeason"][];
            support_price_context: components["schemas"]["SupportPriceContext"];
            /** Not Available */
            not_available: ("wheat" | "cotton" | "irri" | "super_basmati")[];
            /** Is Estimate */
            is_estimate: boolean;
        };
        /** CropPlanSeason */
        CropPlanSeason: {
            /**
             * Season
             * @enum {string}
             */
            season: "RABI" | "KHARIF";
            /**
             * Status
             * @enum {string}
             */
            status: "RANKED" | "TOO_FEW_CROPS" | "NOT_ENOUGH_CURRENT_EVIDENCE";
            /** N Crops */
            n_crops: number;
            /** N Comparable */
            n_comparable: number;
        };
        /** DataSourceInfo */
        DataSourceInfo: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Covers */
            covers: string;
        };
        /**
         * DirectionCall
         * @description Owner B's model: likely up or down over 4 weeks, with no price number (docs/MODEL_CARD.md). Wheat only.
         */
        DirectionCall: {
            /**
             * Call
             * @enum {string}
             */
            call: "UP" | "DOWN";
            /** Validation Accuracy Pct */
            validation_accuracy_pct: number | null;
            /** Model Version */
            model_version: string | null;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /**
             * Source
             * @enum {string}
             */
            source: "shap" | "facts";
            direction?: components["schemas"]["DirectionCall"] | null;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
        };
        /** Farmer */
        Farmer: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Language
             * @enum {string}
             */
            language: "ur" | "en";
            /**
             * District
             * @enum {string}
             */
            district: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Land Area Acres */
            land_area_acres: number | null;
            /** Arhti Commission Pct */
            arhti_commission_pct: number | null;
            /** Alerts Enabled */
            alerts_enabled: boolean;
            /** Crops */
            crops: components["schemas"]["FarmerCropIn"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FarmerCropIn */
        FarmerCropIn: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Preferred Mandi
             * @enum {string}
             */
            preferred_mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Harvest Quantity Maund */
            harvest_quantity_maund: number;
        };
        /** FarmerIn */
        FarmerIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Language
             * @default ur
             * @enum {string}
             */
            language: "ur" | "en";
            /**
             * District
             * @enum {string}
             */
            district: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Land Area Acres */
            land_area_acres?: number | null;
            /** Arhti Commission Pct */
            arhti_commission_pct?: number | null;
            /**
             * Alerts Enabled
             * @default true
             */
            alerts_enabled: boolean;
            /** Crops */
            crops?: components["schemas"]["FarmerCropIn"][];
        };
        /** FarmerUpdate */
        FarmerUpdate: {
            /** Name */
            name?: string | null;
            /** Language */
            language?: ("ur" | "en") | null;
            /** District */
            district?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Land Area Acres */
            land_area_acres?: number | null;
            /** Arhti Commission Pct */
            arhti_commission_pct?: number | null;
            /** Alerts Enabled */
            alerts_enabled?: boolean | null;
            /** Crops */
            crops?: components["schemas"]["FarmerCropIn"][] | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Current Price */
            current_price: number;
            /** Predicted Price */
            predicted_price: number;
            range: components["schemas"]["PriceRange"];
            /** Horizon Weeks */
            horizon_weeks: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "UP" | "DOWN" | "STABLE";
            /**
             * Volatility
             * @enum {string}
             */
            volatility: "STABLE" | "MODERATE" | "VOLATILE";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            /** Model */
            model: string;
            /** Is Stale */
            is_stale: boolean;
            /** Price Unchanged Since */
            price_unchanged_since: string | null;
            direction?: components["schemas"]["DirectionCall"] | null;
            /** History */
            history: components["schemas"]["PricePoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Weekly */
            weekly: components["schemas"]["PricePoint"][];
            /** Seasonal */
            seasonal: components["schemas"]["SeasonalPoint"][];
            /** Sowing Months */
            sowing_months: [
                number,
                number
            ];
            /** Harvest Months */
            harvest_months: [
                number,
                number
            ];
        };
        /** HoldHistory */
        HoldHistory: {
            /** Start Month */
            start_month: number;
            /** Later Month */
            later_month: number;
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /** Loss Pct */
            loss_pct: number;
            /** N */
            n: number;
            /** Wins */
            wins: number;
            /** Median Net Per Maund */
            median_net_per_maund: number;
            /** Worst P10 Net Per Maund */
            worst_p10_net_per_maund: number;
            /** Seasons */
            seasons: components["schemas"]["HoldSeason"][];
        };
        /** HoldSeason */
        HoldSeason: {
            /** Year */
            year: number;
            /** Start Price */
            start_price: number;
            /** Later Price */
            later_price: number;
            /** Net Gain Per Maund */
            net_gain_per_maund: number;
            /** Paid */
            paid: boolean;
        };
        /** Loan */
        Loan: {
            /** Id */
            id: string;
            /** Lender */
            lender: string;
            /** Amount Rs */
            amount_rs: number;
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoanIn */
        LoanIn: {
            /** Lender */
            lender: string;
            /** Amount Rs */
            amount_rs: number;
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
        };
        /** LoanInputItem */
        LoanInputItem: {
            /** Item */
            item: string;
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
            /** Rs Per Acre */
            rs_per_acre: number;
        };
        /** LoanLadderSlice */
        LoanLadderSlice: {
            /**
             * Id
             * @enum {string}
             */
            id: "kissan_card" | "pm_youth" | "akhuwat" | "zarkhez_e" | "bank" | "arhti";
            /** Amount Rs */
            amount_rs: number;
            /** Interest Rs */
            interest_rs: number;
        };
        /** LoanOption */
        LoanOption: {
            /**
             * Id
             * @enum {string}
             */
            id: "kissan_card" | "pm_youth" | "akhuwat" | "zarkhez_e" | "bank" | "arhti";
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /** Max Rs */
            max_rs: number | null;
            /** Eligible */
            eligible: boolean;
            /** Why Not Ur */
            why_not_ur?: string | null;
            /** Why Not En */
            why_not_en?: string | null;
            /** Conditions Ur */
            conditions_ur: string;
            /** Conditions En */
            conditions_en: string;
            /** Source Url */
            source_url: string;
            /** Verified */
            verified: boolean;
        };
        /** LoanPlanResponse */
        LoanPlanResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /** Acres */
            acres: number;
            /** Savings Rs */
            savings_rs: number;
            /** Age */
            age?: number | null;
            /** Months To Harvest */
            months_to_harvest: number;
            /** Input Items */
            input_items: components["schemas"]["LoanInputItem"][];
            /** Input Cost Note */
            input_cost_note: string;
            /** Input Need Rs */
            input_need_rs: number;
            /** Borrow Needed Rs */
            borrow_needed_rs: number;
            /**
             * Harvest Cost Rs
             * @default 0
             */
            harvest_cost_rs: number;
            /** Options */
            options: components["schemas"]["LoanOption"][];
            /** Ladder */
            ladder: components["schemas"]["LoanLadderSlice"][];
            /** Ladder Interest Rs */
            ladder_interest_rs: number;
            /** Harvest Due Rs */
            harvest_due_rs: number;
            /** Uncovered Rs */
            uncovered_rs: number;
            /** Planned Borrow Rs */
            planned_borrow_rs?: number | null;
            /** Planned Lender */
            planned_lender?: ("kissan_card" | "pm_youth" | "akhuwat" | "zarkhez_e" | "bank" | "arhti") | null;
            /** Planned Interest Rs */
            planned_interest_rs?: number | null;
            /** Over Borrow Rs */
            over_borrow_rs?: number | null;
            /**
             * Plan Comparison
             * @enum {string}
             */
            plan_comparison: "NOT_REQUESTED" | "COMPARED" | "INSUFFICIENT_INFORMATION";
            /** Net Impact Rs */
            net_impact_rs?: number | null;
            /** Extra Cost Rs */
            extra_cost_rs?: number | null;
            /** Saving Rs */
            saving_rs?: number | null;
            /** Unpriced Options */
            unpriced_options: ("kissan_card" | "pm_youth" | "akhuwat" | "zarkhez_e" | "bank" | "arhti")[];
            /** Missing Inputs */
            missing_inputs: string[];
            /** Warnings */
            warnings: ("OVER_BORROWING" | "NOT_SMALL_FARMER" | "COST_ESTIMATE" | "UNCOVERED")[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Phone */
            phone: string;
        };
        /** MarginResponse */
        MarginResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Price */
            price: number;
            /** Production Cost */
            production_cost: number;
            /** Cost Confidence */
            cost_confidence: string;
            /** Arhti Pct */
            arhti_pct: number;
            /** Arhti Amount */
            arhti_amount: number;
            /** Profit */
            profit: number;
            /** Support Price */
            support_price: number | null;
            /** Support Status */
            support_status: string | null;
            /** Support Crop Year */
            support_crop_year: string | null;
        };
        /** Meta */
        Meta: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /**
             * Price Type
             * @constant
             */
            price_type: "wholesale";
            /** Crops */
            crops: components["schemas"]["CropInfo"][];
            /** Mandis */
            mandis: components["schemas"]["NamedItem"][];
            /** Series */
            series: components["schemas"]["SeriesInfo"][];
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Horizon Weeks */
            horizon_weeks: number;
            /** Wait Threshold Pct */
            wait_threshold_pct: number;
            /** Interest Pct Per Month */
            interest_pct_per_month: number;
            /** Sources */
            sources: components["schemas"]["DataSourceInfo"][];
        };
        /** NamedItem */
        NamedItem: {
            /** Id */
            id: string;
            /** Name Ur */
            name_ur: string;
            /** Name En */
            name_en: string;
        };
        /** NewsItem */
        NewsItem: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /**
             * Published
             * Format: date
             */
            published: string;
            /**
             * Tag
             * @enum {string}
             */
            tag: "SUPPORT_PRICE" | "PROCUREMENT" | "CAP_OR_BAN" | "IMPORT" | "PRICE_REPORT" | "OTHER";
            /** Crop */
            crop: ("wheat" | "cotton" | "irri" | "super_basmati") | null;
            /** Summary Ur */
            summary_ur: string;
            /** Summary En */
            summary_en: string;
            /** Price Rs Per 40Kg */
            price_rs_per_40kg: number | null;
        };
        /** NewsPriceCheck */
        NewsPriceCheck: {
            /** Amis Price */
            amis_price: number;
            /**
             * Amis Date
             * Format: date
             */
            amis_date: string;
            /** News Price */
            news_price: number;
            /**
             * News Date
             * Format: date
             */
            news_date: string;
            /** News Source */
            news_source: string;
            /** News Url */
            news_url: string;
            /** Difference Pct */
            difference_pct: number;
        };
        /** NewsResponse */
        NewsResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Items */
            items: components["schemas"]["NewsItem"][];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Is Snapshot */
            is_snapshot: boolean;
            /**
             * Tagged By
             * @enum {string}
             */
            tagged_by: "llm" | "rules";
            price_check?: components["schemas"]["NewsPriceCheck"] | null;
        };
        /** OfferCheckRequest */
        OfferCheckRequest: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /** Offer Price */
            offer_price: number;
            /**
             * Quantity Maund
             * @default 100
             */
            quantity_maund: number;
        };
        /** OfferCheckResponse */
        OfferCheckResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Offer Price */
            offer_price: number;
            /** Fair Low */
            fair_low: number;
            /** Fair High */
            fair_high: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "below" | "fair" | "above";
            /** Difference Per Maund */
            difference_per_maund: number;
            /** Difference Total */
            difference_total: number;
            /** Window Days */
            window_days: number;
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
        };
        /** PolicyEvent */
        PolicyEvent: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Tag
             * @enum {string}
             */
            tag: "SUPPORT_PRICE" | "PROCUREMENT" | "CAP_OR_BAN" | "IMPORT" | "PRICE_REPORT" | "OTHER";
            /** Text Ur */
            text_ur: string;
            /** Text En */
            text_en: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
        };
        /** PolicyResponse */
        PolicyResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /** Events */
            events: components["schemas"]["PolicyEvent"][];
        };
        /**
         * PricePoint
         * @description One week. `price` is None for a week with no AMIS price: draw a gap, never join across it.
         */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number | null;
            /**
             * Frozen
             * @default false
             */
            frozen: boolean;
            /**
             * Filled
             * @default false
             */
            filled: boolean;
        };
        /** PriceRange */
        PriceRange: {
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /** Reason */
        Reason: {
            /** Text Ur */
            text_ur: string;
            /** Text En */
            text_en: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "UP" | "DOWN" | "";
        };
        /** SeasonalPoint */
        SeasonalPoint: {
            /** Month */
            month: number;
            /** Index Median */
            index_median: number | null;
            /** Index Min */
            index_min: number | null;
            /** Index Max */
            index_max: number | null;
            /** N Years */
            n_years: number;
        };
        /** SeriesInfo */
        SeriesInfo: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Latest Price */
            latest_price: number;
            /** Is Stale */
            is_stale: boolean;
        };
        /**
         * SupportPriceContext
         * @description The latest wheat SUPPORT_PRICE item from the policy timeline: policy context, not a mandi price and not a
         *     price anyone is promised.
         */
        SupportPriceContext: {
            /**
             * State
             * @enum {string}
             */
            state: "CURRENT" | "OUTDATED" | "UNAVAILABLE";
            event: components["schemas"]["PolicyEvent"] | null;
            /** Age Days */
            age_days: number | null;
            /** Max Age Days */
            max_age_days: number;
            /** Uncertain */
            uncertain: boolean;
            /** Uncertain Window Days */
            uncertain_window_days: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
            farmer: components["schemas"]["Farmer"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaitExit */
        WaitExit: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "SELL_NOW" | "ARHTI_OFFER" | "HOLD";
            /** Mandi */
            mandi?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            /** Per Maund */
            per_maund: number;
            /** Total Rs */
            total_rs: number;
            /** Worst Total Rs */
            worst_total_rs?: number | null;
            /** Cost Rs */
            cost_rs?: number | null;
        };
        /** WaitPlanResponse */
        WaitPlanResponse: {
            /** Data Source */
            data_source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /**
             * Crop
             * @enum {string}
             */
            crop: "wheat" | "cotton" | "irri" | "super_basmati";
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            /**
             * Unit
             * @constant
             */
            unit: "40kg";
            /** Quantity Maund */
            quantity_maund: number;
            /** Cash Need Rs */
            cash_need_rs: number;
            /** Household Spend Rs Month */
            household_spend_rs_month: number;
            /** Other Income Rs Month */
            other_income_rs_month: number;
            /** Loans Due Rs */
            loans_due_rs: number;
            /** Wait Months */
            wait_months: number;
            /**
             * Money
             * @enum {string}
             */
            money: "own" | "bank" | "arhti";
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /**
             * Storage
             * @enum {string}
             */
            storage: "godown" | "bags";
            /** Loss Pct */
            loss_pct: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "SELL_ALL" | "SPLIT" | "HOLD_ALL";
            /** Sell Now Maund */
            sell_now_maund: number;
            /** Hold Maund */
            hold_maund: number;
            /** Exits */
            exits: components["schemas"]["WaitExit"][];
            history: components["schemas"]["HoldHistory"] | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            /** Warnings */
            warnings: ("STALE_PRICE" | "NEWS_PRICE_CONFLICT" | "POLICY_UNCERTAIN" | "HOLD_WHEAT_ONLY" | "CASH_NEED_EXCEEDS_CROP" | "TOO_FEW_SEASONS")[];
            news_check?: components["schemas"]["NewsPriceCheck"] | null;
            /**
             * Prices As Of
             * Format: date
             */
            prices_as_of: string;
            /** Is Stale */
            is_stale: boolean;
        };
        /** WeatherNow */
        WeatherNow: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Tmax C */
            tmax_c: number | null;
            /** Tmin C */
            tmin_c: number | null;
            /** Precip Mm Wk */
            precip_mm_wk: number | null;
            /** Rh Pct */
            rh_pct: number | null;
            /** Precip Mm 4W */
            precip_mm_4w: number | null;
            /** Hot Days Wk */
            hot_days_wk: number | null;
            /** Cached */
            cached: boolean;
            /** Source */
            source: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Attribution */
            attribution: string;
        };
        /** WeatherResponse */
        WeatherResponse: {
            /**
             * Mandi
             * @enum {string}
             */
            mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            weather: components["schemas"]["WeatherNow"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    forecast_api_forecast_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_api_explain_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_weather_api_weather_get: {
        parameters: {
            query: {
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advice_api_advice_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Maund. Default: profile, else 100. */
                quantity_maund?: number | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_mandis_api_compare_mandis_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Maund. Default: profile, else 100. */
                quantity_maund?: number | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_check_api_offer_check_post: {
        parameters: {
            query?: {
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    margin_api_margin_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                price: number;
                arhti_pct?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crop_plan_api_crop_plan_get: {
        parameters: {
            query?: {
                mandi?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
                land_area_acres?: number | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wait_plan_api_wait_plan_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                mandi: "bahawalpur" | "vehari" | "rahim_yar_khan";
                /** @description Maund. Default: profile, else 100. */
                quantity_maund?: number | null;
                /** @description Rs needed now. */
                cash_need_rs?: number;
                /** @description How long the rest could wait. */
                wait_months?: number;
                /** @description Whose money pays for waiting. */
                money?: "own" | "bank" | "arhti";
                /** @description % a year. */
                annual_rate?: number | null;
                storage?: "godown" | "bags";
                /** @description Arhti's offer per 40 kg. */
                offer?: number | null;
                /** @description Household spending a month. */
                household_spend_rs_month?: number;
                /** @description Other steady income a month. */
                other_income_rs_month?: number;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    news_api_news_get: {
        parameters: {
            query?: {
                crop?: ("wheat" | "cotton" | "irri" | "super_basmati") | null;
                mandi?: ("bahawalpur" | "vehari" | "rahim_yar_khan") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_api_policy_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    loan_plan_api_loan_plan_get: {
        parameters: {
            query: {
                crop: "wheat" | "cotton" | "irri" | "super_basmati";
                /** @description Land under this crop. */
                acres: number;
                /** @description Money in hand. */
                savings_rs?: number;
                /** @description For PM Youth eligibility. */
                age?: number | null;
                /** @description What they planned to borrow. */
                planned_borrow_rs?: number | null;
                /** @description Who they planned to borrow from. */
                planned_lender?: ("kissan_card" | "pm_youth" | "akhuwat" | "zarkhez_e" | "bank" | "arhti") | null;
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_loans_api_farmers_me_loans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"][];
                };
            };
        };
    };
    add_my_loan_api_farmers_me_loans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_loan_api_farmers_me_loans__loan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_alerts_api_alerts_run_post: {
        parameters: {
            query?: {
                /** @description Use only data on or before this date. Omit for the latest. */
                as_of?: string | null;
                dry_run?: boolean;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_farmers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_farmers_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farmer"];
                };
            };
        };
    };
    update_me_api_farmers_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farmer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_webhooks_whatsapp_get: {
        parameters: {
            query?: {
                "hub.mode"?: string;
                "hub.verify_token"?: string;
                "hub.challenge"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_webhooks_whatsapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    receive_api_channels_sms_textbee_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    receive_api_channels_sms_simpapp_webhook_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
